/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "server_types.h"

#include <algorithm>

namespace urlserver {

const char* resp::ascii_fingerprint = "28C2ECC89260BADB9C70330FBF47BFA8";
const uint8_t resp::binary_fingerprint[16] = {0x28,0xC2,0xEC,0xC8,0x92,0x60,0xBA,0xDB,0x9C,0x70,0x33,0x0F,0xBF,0x47,0xBF,0xA8};

uint32_t resp::read(::apache::thrift::protocol::TProtocol* iprot) {

  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->doc);
          this->__isset.doc = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->access_count);
          this->__isset.access_count = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->miss_count);
          this->__isset.miss_count = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t resp::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  xfer += oprot->writeStructBegin("resp");

  xfer += oprot->writeFieldBegin("doc", ::apache::thrift::protocol::T_STRING, 1);
  xfer += oprot->writeString(this->doc);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("access_count", ::apache::thrift::protocol::T_I32, 2);
  xfer += oprot->writeI32(this->access_count);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("miss_count", ::apache::thrift::protocol::T_I32, 3);
  xfer += oprot->writeI32(this->miss_count);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(resp &a, resp &b) {
  using ::std::swap;
  swap(a.doc, b.doc);
  swap(a.access_count, b.access_count);
  swap(a.miss_count, b.miss_count);
  swap(a.__isset, b.__isset);
}

} // namespace
