/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef URLproxy_H
#define URLproxy_H

#include <thrift/TDispatchProcessor.h>
#include "server_types.h"

namespace urlserver {

class URLproxyIf {
 public:
  virtual ~URLproxyIf() {}
  virtual void request(resp& _return, const std::string& url) = 0;
  virtual void shutdown() = 0;
};

class URLproxyIfFactory {
 public:
  typedef URLproxyIf Handler;

  virtual ~URLproxyIfFactory() {}

  virtual URLproxyIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(URLproxyIf* /* handler */) = 0;
};

class URLproxyIfSingletonFactory : virtual public URLproxyIfFactory {
 public:
  URLproxyIfSingletonFactory(const boost::shared_ptr<URLproxyIf>& iface) : iface_(iface) {}
  virtual ~URLproxyIfSingletonFactory() {}

  virtual URLproxyIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(URLproxyIf* /* handler */) {}

 protected:
  boost::shared_ptr<URLproxyIf> iface_;
};

class URLproxyNull : virtual public URLproxyIf {
 public:
  virtual ~URLproxyNull() {}
  void request(resp& /* _return */, const std::string& /* url */) {
    return;
  }
  void shutdown() {
    return;
  }
};

typedef struct _URLproxy_request_args__isset {
  _URLproxy_request_args__isset() : url(false) {}
  bool url;
} _URLproxy_request_args__isset;

class URLproxy_request_args {
 public:

  URLproxy_request_args() : url() {
  }

  virtual ~URLproxy_request_args() throw() {}

  std::string url;

  _URLproxy_request_args__isset __isset;

  void __set_url(const std::string& val) {
    url = val;
  }

  bool operator == (const URLproxy_request_args & rhs) const
  {
    if (!(url == rhs.url))
      return false;
    return true;
  }
  bool operator != (const URLproxy_request_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const URLproxy_request_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class URLproxy_request_pargs {
 public:


  virtual ~URLproxy_request_pargs() throw() {}

  const std::string* url;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _URLproxy_request_result__isset {
  _URLproxy_request_result__isset() : success(false) {}
  bool success;
} _URLproxy_request_result__isset;

class URLproxy_request_result {
 public:

  URLproxy_request_result() {
  }

  virtual ~URLproxy_request_result() throw() {}

  resp success;

  _URLproxy_request_result__isset __isset;

  void __set_success(const resp& val) {
    success = val;
  }

  bool operator == (const URLproxy_request_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const URLproxy_request_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const URLproxy_request_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _URLproxy_request_presult__isset {
  _URLproxy_request_presult__isset() : success(false) {}
  bool success;
} _URLproxy_request_presult__isset;

class URLproxy_request_presult {
 public:


  virtual ~URLproxy_request_presult() throw() {}

  resp* success;

  _URLproxy_request_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};


class URLproxy_shutdown_args {
 public:

  URLproxy_shutdown_args() {
  }

  virtual ~URLproxy_shutdown_args() throw() {}


  bool operator == (const URLproxy_shutdown_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const URLproxy_shutdown_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const URLproxy_shutdown_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class URLproxy_shutdown_pargs {
 public:


  virtual ~URLproxy_shutdown_pargs() throw() {}


  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

class URLproxyClient : virtual public URLproxyIf {
 public:
  URLproxyClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  URLproxyClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void request(resp& _return, const std::string& url);
  void send_request(const std::string& url);
  void recv_request(resp& _return);
  void shutdown();
  void send_shutdown();
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class URLproxyProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<URLproxyIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (URLproxyProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_request(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_shutdown(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  URLproxyProcessor(boost::shared_ptr<URLproxyIf> iface) :
    iface_(iface) {
    processMap_["request"] = &URLproxyProcessor::process_request;
    processMap_["shutdown"] = &URLproxyProcessor::process_shutdown;
  }

  virtual ~URLproxyProcessor() {}
};

class URLproxyProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  URLproxyProcessorFactory(const ::boost::shared_ptr< URLproxyIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< URLproxyIfFactory > handlerFactory_;
};

class URLproxyMultiface : virtual public URLproxyIf {
 public:
  URLproxyMultiface(std::vector<boost::shared_ptr<URLproxyIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~URLproxyMultiface() {}
 protected:
  std::vector<boost::shared_ptr<URLproxyIf> > ifaces_;
  URLproxyMultiface() {}
  void add(boost::shared_ptr<URLproxyIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void request(resp& _return, const std::string& url) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->request(_return, url);
    }
    ifaces_[i]->request(_return, url);
    return;
  }

  void shutdown() {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->shutdown();
    }
    ifaces_[i]->shutdown();
  }

};

} // namespace

#endif
